### ISSUE TITLE
CRITICAL: Code in Saab95 and Volvo240 untested

### ISSUE THREAD

**Issue by radams78** [spiros132/TDA553-lab1#11]
The unit tests do not cover any of the code in Saab95 or Volvo240.

**Comment by spiros132** [comment]
There isn't any code that we can test in our Saab95 and Volvo240 classes right now after the changes

**Comment by radams78** [comment]
There is still code in Saab95 and Volvo240, and all the code is certainly testable. Here is one possible unit test:

public void test_move_with_50_percent_gas() {
  Car volvo = new Volvo240();
  volvo.StartEngine();
  volvo.gas(0.5);
  volvo.move();
  assertEquals(1.25, volvo.getCurrentPosition().y, 0.01);
}
